#!/bin/bash

DEFINES="-DDEBUG -DCPU_MKW41Z512VHT4"
INCLUDES="-Isource -I. -ICMSIS -Ifreertos -Istartup -I/Applications/MCUXpressoIDE_10.0.2_411/ide/tools/features/include"
FLAGS="--specs=nosys.specs -O0 -fno-common -g3 -Wall -c -fmessage-length=0 -fno-builtin -ffunction-sections -fdata-sections -mcpu=cortex-m0plus -mthumb"

#---------------------------------

echo "Compiling..."
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "startup/startup_mkw41z4.o" "startup/startup_mkw41z4.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "source/Board_LED.o" "source/Board_LED.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "source/RTOS_Blink.o" "source/RTOS_Blink.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o  "source/mtb.o" "source/mtb.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/croutine.o" "freertos/croutine.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/event_groups.o" "freertos/event_groups.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/fsl_tickless_lptmr.o" "freertos/fsl_tickless_lptmr.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/fsl_tickless_systick.o" "freertos/fsl_tickless_systick.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/heap_4.o" "freertos/heap_4.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/list.o" "freertos/list.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/port.o" "freertos/port.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/queue.o" "freertos/queue.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/tasks.o" "freertos/tasks.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "freertos/timers.o" "freertos/timers.c"
arm-none-eabi-gcc $DEFINES $INCLUDES $FLAGS -o "CMSIS/system_MKW41Z4.o" "CMSIS/system_MKW41Z4.c"

#---------------------------------

echo "Linking..."
arm-none-eabi-gcc --specs=nosys.specs -Xlinker -Map="RTOS_Blink.map" -Xlinker --gc-sections -Xlinker -print-memory-usage -mcpu=cortex-m0plus -mthumb -T RTOS_Blink_Debug.ld -o "RTOS_Blink.axf"  startup/startup_mkw41z4.o  source/Board_LED.o source/RTOS_Blink.o source/mtb.o  freertos/croutine.o freertos/event_groups.o freertos/fsl_tickless_lptmr.o freertos/fsl_tickless_systick.o freertos/heap_4.o freertos/list.o freertos/port.o freertos/queue.o freertos/tasks.o freertos/timers.o  CMSIS/system_MKW41Z4.o

# arm-none-eabi-size "RTOS_Blink.axf";

# find . -name '*.o' -or -name '*.d' | xargs rm
